Sprint 7 solution in file manager
NadezhdaTA/java-kanban pull request #3
Opened 2024-11-19 13:10 UTC by NadezhdaTA

2024-11-19 13:29 UTC, NadezhdaTA commented
Привет! Пыталась сделать так, чтобы пройти все проверки gitHub, но пока не преуспела) раздел CheckStyle мне не поддается))

2024-11-19 14:03 UTC, VadimZharkov commented
> Привет! Пыталась сделать так, чтобы пройти все проверки gitHub, но пока не преуспела) раздел CheckStyle мне не поддается))

Насколько вижу скобочки расставить и переменные нормально поименовать

2024-11-19 14:08 UTC, VadimZharkov commented on src/InMemoryTaskManager.java
int count_NEW = 0;
 int count_IN_PROGRESS = 0;
 int count_DONE = 0;
Такие названия проверку не пройдут.
Нужно
int countNew = 0; и т.д.

2024-11-19 14:10 UTC, VadimZharkov commented on src/InMemoryTaskManager.java
> +    public HashMap<Integer, Task> getTasks() {
Отдавать  HashMap излишнее, по ТЗ нет таких требований

2024-11-19 14:13 UTC, VadimZharkov commented on src/InMemoryHistoryManager.java
> +    public ArrayList<Task> getHistory() {
В этом методе и подобных случаях не нужно менять тип параметра, лучше 
```
public List<Task> getHistory() {
  return new ArrayList<>(historyList);
}
```

2024-11-19 14:15 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +    static File file;
static не нужно, т.к. это поле будет общим у все экземпляров класса, а нам нужно, чтобы у каждого экземпляра был свой файл

2024-11-19 14:17 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +    public void removeSubtaskById(int id) {
`@Override` лучше писать для переопределенных методов

2024-11-19 14:29 UTC, VadimZharkov commented on src/ManagerSaveException.java
> +public class ManagerSaveException extends Exception{
Лучше занаследоваться от RuntimeException

2024-11-19 14:30 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +            try {
Здесь прехватывать не нужно, просто throw new ManagerSaveException(e.getMessage());

2024-11-19 14:30 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +    public void removeFileContent() {
лучше private

2024-11-19 14:39 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +            throw new RuntimeException(e);
Лучше ManagerSaveException

2024-11-20 12:59 UTC, NadezhdaTA commented on src/FileBackedTaskManager.java
> +    FileBackedTaskManager() {
В чем мы выигрываем, передавая в конструктор имя файла?

2024-11-21 05:07 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> +    FileBackedTaskManager() {
То что можно использовать разные файлы у разных экземпляров менеджеров. Появляется гибкость в различных вариантах использования. Например, в обычном варианте использования это один файл, а в тестах - другой.

2024-11-21 05:11 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
> -    @Override
Зачем `@Override` везде убраны? Их наооборот писать нужно, так мы визуально отличаем переопределенные методы от обычных.

2024-11-21 05:13 UTC, VadimZharkov commented on src/FileBackedTaskManager.java
>  public class FileBackedTaskManager extends InMemoryTaskManager implements TaskManager {
implements TaskManager лишнее, т.к. мы наследуемся от InMemoryTaskManager  а он уже реализует интерфейс TaskManager

2024-11-21 05:16 UTC, VadimZharkov commented on src/InMemoryTaskManager.java
> +    public void setNextId(int nextId) {
Лучше protected, чтобы извне никто не мог установить счетчик идентификаторов, а  только лишь класс наследник мог

2024-11-21 05:19 UTC, VadimZharkov requested changes
Еще нужно исправить несколько замечаний.
А также т.к. файлов становится все больше, то нужно улучшить структуру проекта. Вынеси тесты в отдельную папку и сгруппируй классы по пакетам tasks и managers

2024-11-21 11:09 UTC, NadezhdaTA commented on src/FileBackedTaskManager.java
> -    @Override
потому что я стормозила) неправильно поняла твое замечание

2024-11-21 11:49 UTC, VadimZharkov approved these changes

2024-12-12 09:53 UTC, merged